### ISSUE TITLE
suí- koo-niû 就共連字符當做減號

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7#658]
原因：
有時仔拄著 ke 拍連字符、落勾羅馬字 a̍h-sī 換逝。
```txt
suí- koo-niû
```

**Comment by sih4sing5hong5** [comment]
愛改 https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/blob/master/%E8%A9%A6%E9%A9%97/%E8%A7%A3%E6%9E%90%E6%95%B4%E7%90%86/Test%E6%8B%86%E6%96%87%E5%88%86%E6%9E%90%E5%99%A8%E9%80%A3%E5%AD%97%E7%AC%A6%E5%96%AE%E5%85%83%E8%A9%A6%E9%A9%97.py ê定義
