### ISSUE TITLE
疑問：句、集、組的意思

### ISSUE THREAD

**Issue by YauHsien** [i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7#683]
（歹勢，我不熟悉打字寫台文；且用華文以流利表達疑問。）
請問
如這處[集、組的說明](https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/blame/master/%E6%96%87%E4%BB%B6/%E5%9F%BA%E6%9C%AC%E7%89%A9%E4%BB%B6.md#L24)，所謂「集」是指集合嗎？

`組`在我理解是 options 的意思，而說「這些`組`是代表這個語句在這個`集`，有多個`組`可以選，但是整個語句只能用其中一個`組`」，所以，我覺得是說：在`集`裡頭是 multi-choice 選一個`組`來用。但是，`句`裡頭包含一個或多個`集`，我想知道，多個`集`的彼此關係是互斥 (exclusive) 嗎？

因為說明書的例子恰好沒顯明`集`與`組`的情況。

我舉個例子來問得更詳細：若讀三個字「水埔頭」，我猜，至少產生二個`集`：一是
```
 { '集': [ { '組': [ { '詞': [ { '字': '水' }, { '字': '埔' } ] },
                     { '詞': [ { '字': '頭' } ] },
           { '組': [ { '詞': [ { '字': '水' } ] },
                     { '詞': [ { '字': '埔' }, { '字': '頭' } ] } ] }
```
，而二是
```
 { '集': [ { '組': [ { '詞': [ { '字': '水' }, { '字': '埔' }, { '字': '頭' } ] } ] } ] }``
```
；是否如此？

**Comment by sih4sing5hong5** [comment]
> 請問
> 如這處[集、組的說明](https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/blame/master/%E6%96%87%E4%BB%B6/%E5%9F%BA%E6%9C%AC%E7%89%A9%E4%BB%B6.md#L24)，所謂「集」是指集合嗎？

是，`集合`ê意思

 
> `組`在我理解是 options 的意思，而說「這些`組`是代表這個語句在這個`集`，有多個`組`可以選，但是整個語句只能用其中一個`組`」，所以，我覺得是說：在`集`裡頭是 multi-choice 選一個`組`來用。但是，`句`裡頭包含一個或多個`集`，我想知道，多個`集`的彼此關係是互斥 (exclusive) 嗎？

`集`內底一定ài有`組`，kāng`集`內底ê組是`互斥 (exclusive) `。
所以tī程式會看著

https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/blob/3b87b1771359b0a8a18805100e53e21011b3028e/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E5%B7%A5%E5%85%B7/%E5%9F%BA%E6%9C%AC%E7%89%A9%E4%BB%B6/%E9%9B%86.py#L36-L41

`集`kah`組`是10冬前考慮技術限制，配合辭典、語言模型[標漢字羅馬字](https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/blob/master/%E8%A9%A6%E9%A9%97/%E6%95%B4%E5%90%88%E8%A9%A6%E9%A9%97/Test%E6%A8%99%E5%85%A8%E6%BC%A2%E5%85%A8%E7%BE%85%E6%95%B4%E5%90%88%E8%A9%A6%E9%A9%97.py)。現此時攏用deep learning，抑是lattice，這種設計就較bô必要--ah，阮有piànn重要ê功能到套件[KeSi](https://github.com/i3thuan5/KeSi)。

> 因為說明書的例子恰好沒顯明`集`與`組`的情況。
> 
> 我舉個例子來問得更詳細：若讀三個字「水埔頭」，我猜，至少產生二個`集`：一是
> 
> ```
>  { '集': [ { '組': [ { '詞': [ { '字': '水' }, { '字': '埔' } ] },
>                      { '詞': [ { '字': '頭' } ] },
>            { '組': [ { '詞': [ { '字': '水' } ] },
>                      { '詞': [ { '字': '埔' }, { '字': '頭' } ] } ] }
> ```
> 
> ，而二是
> 
> ```
>  { '集': [ { '組': [ { '詞': [ { '字': '水' }, { '字': '埔' }, { '字': '頭' } ] } ] } ] }``
> ```

`組`下底ê結構會影響著`看語句()`、`看音()`、`看語句()`ê行為，因為台文書寫會kah 斷詞有tī-tāi

**Comment by YauHsien** [comment]
勞力
