### ISSUE TITLE
說明文件个 URL 連無--矣

### ISSUE THREAD

**Issue by LyLiou** [i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7#687]
https://sih4sing5hong5.github.io/tai5-uan5_gian5-gi2_kang1-ku7

**Comment by iunn-sh** [comment]
Fixed in https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/pull/688 -> this issue could be closed?

**Comment by sih4sing5hong5** [comment]
> Fixed in #688 -> this issue could be closed?

多謝
